apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
    scrape_configs:
      - job_name: FiapMetrics
        metrics_path: /metrics
        static_configs:
          - targets:
            - 'api-service:8080'
