apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  labels:
    app: zabbix-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-pgsql:ubuntu-latest
          ports:
            - containerPort: 10051
          env:
            - name: DB_SERVER_HOST
              value: "postgres-service"
            - name: DB_SERVER_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "102030"
            - name: POSTGRES_DB
              value: "zabbix"
          volumeMounts:
            - name: zabbix-server-data
              mountPath: /var/lib/zabbix
            - name: zabbix-snmptraps-data
              mountPath: /var/lib/zabbix/snmptraps
            - name: zabbix-export-data
              mountPath: /var/lib/zabbix/export
      volumes:
        - name: zabbix-server-data
          persistentVolumeClaim:
            claimName: zabbix-server-data
        - name: zabbix-snmptraps-data
          persistentVolumeClaim:
            claimName: zabbix-snmptraps-data
        - name: zabbix-export-data
          persistentVolumeClaim:
            claimName: zabbix-export-data