apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  labels:
    app: zabbix-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-pgsql:ubuntu-latest
          envFrom:
            - configMapRef:
                name: zabbix-server-config
            - secretRef:
                name: zabbix-server-secret
          ports:
            - containerPort: 10051
          volumeMounts:
            - name: zabbix-server-data
              mountPath: /var/lib/zabbix
      volumes:
        - name: zabbix-server-data
          persistentVolumeClaim:
            claimName: zabbix-server-pvc
