apiVersion: v1
kind: Service
metadata: 
  name: zabbix-server-service
spec:
  type: NodePort
  selector:
    app: zabbix-server
  ports: 
    - port: 10051
      targetPort: 10051
      nodePort: 30101