version: '3.8'

services:
  worker.contatos:
    image: igorsallowicz/techchallenge_desafio_4:worker_contato_latest
    build: 
      context: .
      dockerfile: ./src/Workers/Fiap.TechChallenge.Fase3.Contato/Dockerfile
    ports:
      - "8084:8084"
    networks:
      - fiap-network
      
  worker.persistencia:
    image: igorsallowicz/techchallenge_desafio_4:worker_persistencia_latest
    build: 
      context: .
      dockerfile: ./src/Workers/Fiap.TechChallenge.Fase3.Persistencia/Dockerfile
    ports:
      - "8082:8082"
    networks:
      - fiap-network

  worker.usuario:
    image: igorsallowicz/techchallenge_desafio_4:worker_usuario_latest
    build: 
      context: .
      dockerfile: ./src/Workers/Fiap.TechChallenge.Fase3.Usuario/Dockerfile
    ports:
      - "8083:8083"
    networks:
      - fiap-network
     
networks:
  fiap-network:
    driver: bridge
