apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-techchallenge-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-techchallenge
  template:
    metadata:
      labels:
        app: api-techchallenge
    spec:
      containers:
      - name: api-techchallenge-container
        image: igorsallowicz/techchallenge_desafio_4:api_latest
        envFrom:
          - secretRef:
              name: postgres-secret
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"  
            memory: "512Mi"
