apiVersion: v1
kind: Service
metadata:
  name: api-techchallenge-service
spec:
  type: NodePort
  selector:
    app: api-techchallenge
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30004
