apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-agent-config
data:
  zabbix_agentd.conf: |
    LogFile=/var/log/zabbix/zabbix_agentd.log
    LogFileSize=0
    DebugLevel=3
    Server=zabbix-server-service
    ServerActive=zabbix-server-service:10051
    Hostname=zabbix-agent
    Include=/etc/zabbix/zabbix_agentd.d/*.conf
