apiVersion: apps/v1
kind: Deployment
metadata: 
  name: zabbix-agent
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: zabbix-agent
  template: 
    metadata: 
      labels: 
        app: zabbix-agent
    spec:
      containers:
      - name: zabbix-agent
        image: zabbix/zabbix-agent:latest
        envFrom: 
        - configMapRef:
            name: zabbix-agent-config-map
        volumeMounts:
        - name: zabbix-agent-data
          mountPath: /rootfs:ro
        - name: zabbix-agent-root-data
          mountPath: /var/run
      volumes:
      - name: zabbix-agent-data
        persistentVolumeClaim:
          claimName: zabbix-agent-pvc
      - name: zabbix-agent-root-data
        persistentVolumeClaim:
          claimName: zabbix-agent-root-pvc