apiVersion: v1
kind: Service
metadata:
  name: zabbix-agent-service
  labels:
    app: zabbix-agent
spec:
  selector:
    app: zabbix-agent
  ports:
  - protocol: TCP
    port: 10050
    targetPort: 10050