apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: dGVjaGNoYWxsZW5nZQ==    # "user" codificado em Base64
  RABBITMQ_DEFAULT_PASS: dGVjaGNoYWxsZW5nZQ==  # "password" codificado em Base64
  RABBITMQ_ERLANG_COOKIE: dGVjaGNoYWxsZW5nZQ==