apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: NodePort
  selector:
    app: rabbitmq  # Seleciona Pods com o label app: rabbitmq
  ports:
    - name: rabbitmq-5672
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: rabbitmq-15672
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 30002
      