apiVersion: v1
kind: Secret
metadata:
  name: worker-secret
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: dGVjaGNoYWxsZW5nZQ==    # "user" codificado em Base64
  RABBITMQ_DEFAULT_PASS: dGVjaGNoYWxsZW5nZQ==  # "password" codificado em Base64
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: MTAyMDMw