{
 "title": "Fiap Monitoramento",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Status API",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"api-techchallenge-service:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requisições Último Minuto.",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total[1m]))",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Requisições Últimas 1h.",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requisições Últimas 24h.",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Contagem de Requisições por Status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(code) (http_requests_received_total{code=\"200\"})",
     "legendFormat": "200"
    },
    {
     "expr": "sum by(code) (http_requests_received_total{code=\"400\"})",
     "legendFormat": "400"
    },
    {
     "expr": "sum by(code) (http_requests_received_total{code=\"401\"})",
     "legendFormat": "401"
    },
    {
     "expr": "sum by(code) (http_requests_received_total{code=\"404\"})",
     "legendFormat": "404"
    }
   ]
  }
 ]
}