name: TechChallengeFase4 - .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  setup-k8s:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checar o repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Passo 2: Instalar KIND e kubectl
      - name: Install KIND and kubectl
        run: |
          curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/v0.18.0/kind-linux-amd64
          chmod +x kind
          sudo mv kind /usr/local/bin/kind

          curl -LO "https://dl.k8s.io/release/v1.27.0/bin/linux/amd64/kubectl"
          sudo chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      # Passo 3: Criar o cluster Kubernetes com KIND
      - name: Create Kubernetes cluster with KIND
        run: |
          kind create cluster --name my-cluster --wait 5m

      # Passo 4: Verificar o status do cluster Kubernetes
      - name: Verify Kubernetes cluster
        run: |
          kubectl cluster-info      

      # Passo 5: Aplicar recursos Kubernetes (opcional)
      - name: Apply Kubernetes resources
        run: |
          kubectl apply -f k8s/api/
          kubectl apply -f k8s/postgres/
          kubectl apply -f k8s/rabbitmaq/ 

      # Passo 6: Verificar namespace
      - name: Verificar namespace dos pods
        run: |
          kubectl get pods --all-namespaces

      # Passo 6: Verificar pods e serviços
      - name: Get Kubernetes pods and services
        run: |
          kubectl get pods
          kubectl get services
      
      # Passo 6: Verificar namespace
      - name: Verificar namespace
        run: |
          kubectl get namespaces

      # Passo 7: Aguardo dos Pods estarem OK
      - name: Wait for all pods to be running
        run: |
          kubectl wait --for=condition=ready pod --all --namespace=default --timeout=300s

        # Passo 6: Verificar pods e serviços
      - name: Get Kubernetes pods and services
        run: |
          kubectl get pods
          kubectl get services

      # Passo 8: Liberando Portas
      - name: Port-forward Kubernetes services
        run: |
          kubectl port-forward svc/rabbitmq-service 5672:5672
          kubectl port-forward svc/postgres-service 5432:5432

      # Passo 9: Deletar o cluster KIND após o uso
      - name: Delete Kubernetes cluster with KIND
        run: |
          kind delete cluster --name my-cluster

      - name: Saída Final Tech Challenge Fase 4
        run: echo "Build projeto API e Kubernetes para a validação do Tech Challenge Fase 4."
