name: TechChallengeFase4 - .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  setup-k8s:
    runs-on: ubuntu-latest
    
    steps:
      # Passo 1: Checar o repositório
      - name: Kubernetes
        uses: actions/checkout@v3

      # Passo 2: Instalar dependências para o Minikube e kubectl
      - name: Install Minikube
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https
          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          echo "deb https://storage.googleapis.com/download.minikube.dev/deb stable main" | sudo tee /etc/apt/sources.list.d/minikube.list
          sudo apt-get update
          sudo apt-get install -y minikube

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.27.0/bin/linux/amd64/kubectl"
          sudo chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      # Passo 3: Iniciar o Minikube
      - name: Start Minikube
        run: |
          minikube start --driver=docker
          kubectl config use-context minikube

      # Passo 4: Testar o Kubernetes
      - name: Verify Kubernetes cluster
        run: |
          kubectl cluster-info

      # Passo 5: Aplicar recursos Kubernetes (opcional)
      - name: Apply Kubernetes resources
        run: |
          kubectl apply -f k8s/api/
          kubectl apply -f k8s/postgres/
          kubectl apply -f k8s/rabbimaq/      

      # Passo 6: Verificar pods e serviços
      - name: Get Kubernetes pods and services
        run: |
          kubectl get pods
          kubectl get services

      - name: Saída Final Tech Challenge Fase 4
        run: echo "Build projeto API e Kubernetes para a validação do Tech Challenge Fase 4."
